import "@/css/embed.css";
import "@/css/embed-loader.css";
export const metadata = {
  title: "Event",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
